import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="flex items-center justify-between px-8 py-4 border-b border-gray-200 mb-8">
          <Link href="/" className="font-bold text-2xl no-underline text-inherit">
            Next.js E-Commerce
          </Link>
          <div className="flex gap-6">
            <Link href="/products" className="no-underline text-inherit">Products</Link>
            <Link href="/cart" className="no-underline text-inherit">Cart</Link>
            <Link href="/checkout" className="no-underline text-inherit">Check Out</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
